### ISSUE TITLE
Illegal Token Error on Win7 64bit as well as OSX 10.10.1

### ISSUE THREAD

**Issue by davidjost** [iconic/illustrator-svg-exporter#7] opened 2015-01-27 18:45 UTC
Recreate like so: 
- Latest Illustrator CC on Win7 64bit / Mac OSX 10.10.1
- Install file as instructed
- Start Illustrator
- File -> New (Web template, 72dpi)
- Draw simple square
- Rename layer or object to: anything.svg
- Run script, either via menu or as 'run script...'

This error message pops up:
**Error 60: not conform (illegal Token).
Line: 584
->         < td id="LC34" class="blob-code js-file-line" > < span class="pl-k" > try < /span > { < /td >**

**Comment by somerandomdude** [comment] 2015-01-27 19:05
Hey @Gregmcor, thanks for sending this along. I'm not able to reproduce this, I'm wondering if could you send the Illustrator file?

**Comment by davidjost** [comment] 2015-01-27 19:32
You've got mail.

**Comment by somerandomdude** [comment] 2015-01-27 19:49
Thanks @Gregmcor, we'll get to the bottom of this.

**Comment by mgrn0** [comment] 2015-02-11 12:21
I had the same error, I re-downloaded the script (instead of save as) and double checked that the content of the file was exactly like the file on github. seems like it was corrupted (or changed) during download the first time I downloaded it.

You could try to download the zipped repo to be on the safe side.

**Comment by somerandomdude** [comment] 2015-02-11 16:55
Oh, that's great to know! We still haven't been able to replicate it, so perhaps it's just a downloading issue. @Gregmcor, would you be able to give this a try?

Thanks @mgrn0!

**Comment by somerandomdude** [comment] 2015-02-17 19:02
@Gregmcor, I'm going to close this for now. Please submit another issue if continue to run into problems.

**Closed as completed by somerandomdude** 2015-02-17 19:02 UTC

**Comment by heinsman** [comment] 2015-02-19 19:08
I am getting the same error. Any solution?

**Comment by mgrn0** [comment] 2015-02-19 19:21
did you double check that the download is correct / not corrupted (e.g. 
by dowloading the repo as a ((complete)) zip file and not just the 
script itself?

**Comment by heinsman** [comment] 2015-02-19 19:23
Yeah, I deleted my question after I realized that was the solution. I can’t figure out how to actually export the .SVGs but I’m not getting the error anymore.

Thanks!
- Mark

**Comment by heinsman** [comment] 2015-02-19 19:28
I got it working, thanks!
- Mark
